# Generated by Django 3.0.4 on 2020-05-05 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerypage',
            name='gallery_collection',
            field=models.ForeignKey(help_text='Choose the image gallery you created in "Settings - Collections".', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to='wagtailcore.Collection'),
        ),
    ]
