# Generated by Django 3.0.4 on 2020-05-06 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('gallery', '0003_auto_20200505_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerypage',
            name='gallery_listing_page_image',
            field=models.ForeignKey(help_text='Image from this collection that will appear on Gallery Listing Page. Image will be cropped to 1000px by 600px.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
