# Generated by Django 3.0.4 on 2020-05-04 14:43

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formfield',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='contact_page_image',
            field=models.ForeignKey(help_text='Image will be cropped to 500px by 298px.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='thank_you_text',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Text shown on the form submission landing page.'),
        ),
    ]
