# Generated by Django 3.0.4 on 2020-04-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200429_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='button_text',
            field=models.CharField(default='Read More...', help_text='Text shown on the button, 50 Chars max length.', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='lead_text',
            field=models.CharField(blank=True, help_text='Subheading text under the banner title, 250 Chars max length.', max_length=250),
        ),
    ]
