# Generated by Django 3.0.4 on 2020-04-30 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200430_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='banner_background_image',
        ),
    ]
