# Generated by Django 3.0.4 on 2020-05-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200508_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='keywords',
            field=models.TextField(blank=True, help_text='Optional comma separated list of keywords to describe the content of this page.'),
        ),
    ]
