# Generated by Django 3.0.4 on 2020-05-04 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, help_text='Enter Company Facebook URL')),
                ('youtube', models.URLField(blank=True, help_text='Enter Company YouTube URL')),
                ('instagram', models.URLField(blank=True, help_text='Enter Company Instagram URL')),
                ('twitter', models.URLField(blank=True, help_text='Enter Company Twitter URL')),
                ('linkedin', models.URLField(blank=True, help_text='Enter Company LinkedIn URL')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FooterCTASettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('subtitle', models.TextField(null=True)),
                ('button_text', models.CharField(help_text='30 Character Max.', max_length=30, null=True)),
                ('button_external_page', models.URLField(blank=True, help_text='Enter an external page url or choose an internal page link.', null=True)),
                ('button_internal_page', models.ForeignKey(blank=True, help_text='Select an optional internal page link.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_phone', models.CharField(blank=True, help_text='Enter an optional contact phone number.', max_length=12, null=True)),
                ('contact_email', models.EmailField(blank=True, help_text='Enter an optional contact email address.', max_length=254, null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
